version: '2'
services:
  apache-php:
    image: smachara2/apache-php7:latest
    ports:
     - "8080:80"
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
     - ./db:/var/lib/mysql
    ports:
     - "3306:3306"
    networks:
     - appnet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
     - "80:80"
    links:
      # for mysql container
     - "db:db"
networks:
  appnet:
    driver: "bridge"
volumes:
  db:
    driver: "local"

